language: python
python:
  - "3.4"
install: "pip install -r requirements.txt"
before_install:
    - pip install --upgrade pip
    - pip install --upgrade pytest pytest-cov
script:
    - python manage.py migrate
    - pytest easy_login/tests.py
